/*
 * Teller.java
 *
 */
/**
 *
 * @author  Administrator
 */
public class Teller extends javax.swing.JFrame {    
    /** Creates new form Teller */
    private Account myAccount;
    
    public Teller() {
        initComponents();
    }
        
    public Teller(String str, Account acc) {
        super(str);
        this.setName("xx"+str);
        myAccount = acc;
        initComponents();
        setVisible(true);
        name.setText(acc.getName());
        myTextArea.append("Teller m.c.: ----" + "\n");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        money = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTextArea = new javax.swing.JTextArea();
        bottom = new javax.swing.JPanel();
        DepositBu = new javax.swing.JButton();
        WithdrawBu = new javax.swing.JButton();
        BalanceBu = new javax.swing.JButton();
        QuitBu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jLabel1.setText("Cuenta: ");
        top.add(jLabel1);

        name.setColumns(10);
        top.add(name);

        jLabel2.setText("Cantidad a depositar o retirar: ");
        top.add(jLabel2);

        money.setColumns(10);
        money.setText("0.0");
        top.add(money);

        getContentPane().add(top, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        myTextArea.setColumns(40);
        myTextArea.setRows(12);
        jScrollPane1.setViewportView(myTextArea);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        bottom.setBackground(new java.awt.Color(255, 204, 204));

        DepositBu.setBackground(new java.awt.Color(0, 204, 255));
        DepositBu.setText("Deposit");
        DepositBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBuActionPerformed(evt);
            }
        });

        WithdrawBu.setBackground(new java.awt.Color(204, 204, 0));
        WithdrawBu.setText("Withdraw");
        WithdrawBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawBuActionPerformed(evt);
            }
        });

        BalanceBu.setBackground(new java.awt.Color(51, 255, 51));
        BalanceBu.setText("Balance");
        BalanceBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceBuActionPerformed(evt);
            }
        });

        QuitBu.setBackground(new java.awt.Color(255, 51, 51));
        QuitBu.setText("Quit");
        QuitBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitBuActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout bottomLayout = new org.jdesktop.layout.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bottomLayout.createSequentialGroup()
                .add(73, 73, 73)
                .add(DepositBu)
                .add(18, 18, 18)
                .add(WithdrawBu)
                .add(18, 18, 18)
                .add(BalanceBu)
                .add(18, 18, 18)
                .add(QuitBu)
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bottomLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(bottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(BalanceBu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(QuitBu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(WithdrawBu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(DepositBu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(bottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitBuActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_QuitBuActionPerformed

    private void BalanceBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceBuActionPerformed
        double moneyValue = 0.0;
        CajeAuto accion = new CajeAuto( myAccount, myTextArea, 'B', moneyValue);
        accion.runMain();
        myTextArea.append("Balance: ----" + "\n");
    }//GEN-LAST:event_BalanceBuActionPerformed

    private void WithdrawBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawBuActionPerformed
        double moneyValue = Double.parseDouble(money.getText());
        CajeAuto accion = new CajeAuto( myAccount, myTextArea, 'W', moneyValue);
        accion.runMain();
        myTextArea.append("Withdraw: ----" + "\n");
    }//GEN-LAST:event_WithdrawBuActionPerformed

    private void DepositBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBuActionPerformed
        double moneyValue = Double.parseDouble(money.getText());
        CajeAuto accion = new CajeAuto( myAccount, myTextArea, 'D', moneyValue);
        accion.runMain();
        Thread abcxyz = Thread.currentThread();
        myTextArea.append("Deposit: ----" + "\n");
    }//GEN-LAST:event_DepositBuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teller().setVisible(true);
            }
        });
    }
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BalanceBu;
    private javax.swing.JButton DepositBu;
    private javax.swing.JButton QuitBu;
    private javax.swing.JButton WithdrawBu;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField money;
    private javax.swing.JTextArea myTextArea;
    private javax.swing.JTextField name;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
    
}
